### DISCUSSION TITLE
Support for Adaptive Lighting Custom Component

### DISCUSSION THREAD

**Discussion by Pythm** [Pythm/ad-Lightwand#12] [Announcements]
## What's Changed
This release starts the support to use [Adaptive Lighting ](https://github.com/basnijholt/adaptive-lighting/tree/main) custom component to control your brightness and color control for automation, motion or mode with setting state to 'adaptive'.

There is no need to configure Adaptive Lighting with 'detect_non_ha_changes' when you set it up. Lightwand will set manual control in the provided switch "Adaptive Lighting" that you'll need to define in your room with: 
```yaml
  adaptive_switch: switch.adaptive_lighting_yourName
```

The normal 'automations' is a list. Minimum configuration is with:
```yaml
      automations:
      - state: adaptive
```
To use when motion configure with:
```yaml
      motionlights:
        state: adaptive
```
Both 'automations' and 'motionlights' support list with times and states so you can configure Adaptive Lighting only to be active during specific times if needed to.

To use in mode configure with:
```yaml
      light_modes:
        - mode: your_mode
          state: adaptive
```

Automatic setting of Adaptive Lighting's "Sleep Mode" is not implemented. If you plan to use this make sure that your automation or mode is set to the adaptive state.

I do not use Adaptive Lighting actively so please report any unwanted behaviour.

### Other bugfixes:
- Zigbee2mqtt version 2.0.0 does no longer support 'illuminance_lux' for illuminance values. This has been updated in the code to support 'illuminance'.
- Fixed bug where motion was already detected resulting in not turning brightness up when selecting new light mode with higher brightness.

<hr /><em>This discussion was created from the release <a href='https://github.com/Pythm/ad-Lightwand/releases/tag/v1.3.3'>Support for Adaptive Lighting Custom Component</a>.</em>

**Comment by pointlevel** [comment]
Thanks for including adaptive lighting in the app, i believe the config will be a lot smaller and easier with including the benefit of the circadian lighting.

So, im trying to config my kitchen that has lights that are "glowing" when lux is met and then lights up when motion.
```yaml
adaptive_switch: switch.adaptive_lighting_kitchen_motion

MQTTLights:
    - lights:
        - zigbee2mqtt/Kitchen Island Lamps
        - zigbee2mqtt/Kitchen Cookerhood Lamps

      automations: # Define some light for normal automation when motion is not detected/constrained.
        - state: adaptive
      
      motionlights:
        state: adaptive
        offset: 100
```
I have this adaptive config:
```yaml
- name: Kitchen Motion
  lights:
    - light.kitchen_island_lamps
    - light.kitchen_cookerhood_lamps
  min_brightness: 5
  max_brightness: 30
  skip_redundant_commands: true
  interval: 10
```

But this will not work to turn up the lights when motion. I have also tried:
```yaml
motionlights:
   state: turn_on
   offset: 100
```
...with no luck. Am i misunderstanding something here?

**Reply by Pythm** [reply]
Currently the adaptive state is kind of turning over control to Adaptive Lighting and nothing more. So you basically put "Lightwand" app on hold/pause when it comes to adjusting brightness/color.

I can look into programming offset to read the brightness and then apply, but that will not adjust color temp or brightness further during that state.

Another question is if it would be the same light if you turn the brightness up 100 compared to setting Adaptive max brightness to 130? I have not looked into how they calculate color temps etc...

**Comment by pointlevel** [comment]
Min and max_brightness in adaptive lightning is procentual(0-100), not brightness (0-254). I believe i have to maximize the brightness in adaptive lighting to the max in "idle"-state. Because i dont want the lights to be any brighter during no_motion.
Its working if i do this for example: 

```yaml
motionlights:
   - time: "00:00:00"
       light_data:
         brightness: 200
         transition: 1
```
Of course its not variable during the day in this way, so be able to set an offset to the adaptive would be great.

Is it not possible to use adaptive as state in the motionlights, and when there is an offset, it adds the offset to only the actual brightness and still adjusting both the colortemp and brightness without setting the light in manual? I understand if its not possible, but i need to ask those  stupid questions :)
