### DISCUSSION TITLE
Define Adaptive Lighting for light instead of room

### DISCUSSION THREAD

**Discussion by Pythm** [Pythm/ad-Lightwand#15] [Announcements]
You can now define adaptive lighting for each light in addition to room, if you want to use multiple Adaptive lighting settings in your room.

```yaml
  # The swiches can be configured in the room
  adaptive_switch: switch.adaptive_lighting_yourName
  adaptive_sleep_mode: switch.adaptive_lighting_sleep_mode_yourName
  # Or in lights
    - lights:
      - light.yourLight
      adaptive_switch: switch.adaptive_lighting_yourName
      adaptive_sleep_mode: switch.adaptive_lighting_sleep_mode_yourName
```

Fixed the bug where max and min brightness was not set in mode.

<hr /><em>This discussion was created from the release <a href='https://github.com/Pythm/ad-Lightwand/releases/tag/v1.3.5'>Define Adaptive Lighting for light instead of room</a>.</em>
