### ISSUE TITLE
Calling all lights simultaneously results in too much traffic on the Zigbee network

### ISSUE THREAD

**Issue by pointlevel** [Pythm/ad-Lightwand#10]
Hello,

Sometimes my window-lights doesnt turn on when im arriving home. I Have also noticed some time they dont  turn off when departing.
Pasting my config below (a lot copied from your kitchen-config), and its the light.kitchen_shell_lights. Motion is working

```yaml
kitchen:
  module: lightwand
  class: Room
  json_path: /homeassistant/.storage/

  OutLux_sensor: sensor.outdoor_lux

  motion_sensors:
    - motion_sensor: binary_sensor.activity_in_kitchen
      delay: 5
    - motion_sensor: input_boolean.fake_activity_in_kitchen
      delay: 5

  Lights:
    - lights:
        - light.kitchen_motion_lights

      automations: # Define some light for normal automation when motion is not detected/constrained.
        - time: "00:00:00"
          light_data:
            brightness: 5
            transition: 3
        - time: "05:30:00"
          light_data:
            brightness: 50
            transition: 3
            color_temp_kelvin: 3000
        - time: "sunrise - 00:40:00"
          dimrate: 1
          light_data:
            brightness: 60
            transition: 3
        - time: "08:30:00"
          orLater: "sunrise + 00:15:00" # Want to keep brightness at 80 until 08:30 or if sun rises later it will keep 80 until 15 minutes past sunrise.
          light_data:
            brightness: 50
            transition: 3
        - time: "sunrise + 01:30:00"
          state: turn_off
          light_data: # Input light_data even if state is turn_off if you have modes with offset +-
            brightness: 50
            transition: 3
        - time: "sunset - 01:30:00"
          light_data:
            brightness: 40
            transition: 3
            color_temp_kelvin: 2700
        - time: "sunset + 00:30:00"
          orLater: "21:00:00"
          dimrate: 2 # Will start to dim from previous brightness (40) - 1 per x minutes. In this case every 2 minutes.
          light_data:
            brightness: 5
            transition: 3

      motionlights:
        - time: "00:00:00"
          light_data:
            brightness: 5
            transition: 3
        - time: "06:00:00"
          light_data:
            brightness: 80
            transition: 3
        - time: "06:50:00"
          light_data:
            brightness: 160
            transition: 3
        - time: "07:30:00"
          orLater: "sunrise - 00:20:00"
          light_data:
            brightness: 180
            transition: 3
        - time: "sunrise + 01:00:00"
          light_data:
            brightness: 120
            transition: 3
        - time: "21:00:00"
          orLater: "sunset + 00:30:00"
          dimrate: 2
          light_data:
            brightness: 5
            transition: 3

      light_modes:
        - mode: cooking
          state: turn_on
          offset: 130

      lux_constraint: 5000

    - lights:
        - light.kitchen_shell_lights
      automations:
        - time: "00:00:00"
          light_data:
            brightness: 5
            transition: 3
        - time: "05:30:00"
          light_data:
            brightness: 50
            transition: 3
            color_temp_kelvin: 3000
        - time: "sunrise - 00:40:00"
          dimrate: 1
          light_data:
            brightness: 60
            transition: 3
        - time: "08:30:00"
          orLater: "sunrise + 00:15:00" # Want to keep brightness at 80 until 08:30 or if sun rises later it will keep 80 until 15 minutes past sunrise.
          light_data:
            brightness: 50
            transition: 3
        - time: "sunrise + 01:30:00"
          state: turn_off
          light_data: # Input light_data even if state is turn_off if you have modes with offset +-
            brightness: 50
            transition: 3
        - time: "sunset - 01:30:00"
          light_data:
            brightness: 40
            transition: 3
            color_temp_kelvin: 2700
        - time: "sunset + 00:30:00"
          orLater: "21:00:00"
          dimrate: 2 # Will start to dim from previous brightness (40) - 1 per x minutes. In this case every 2 minutes.
          light_data:
            brightness: 5
            transition: 3

      light_modes:
        - mode: on_kitchen
          state: turn_on

      lux_constraint: 3000
```

Some history:

![Skärmbild 2024-11-18 163840](https://github.com/user-attachments/assets/46d292ba-9988-43f8-8df1-866fe0335739)

**Comment by Pythm** [comment]
I have (and you have copied) a "state: turn_off" between sunrise +01:30 and sunset -01:30.

The reason why I have a state turn off and light data, is that I have also some modes with offset that will turn on light in that periode. Like you have in the other light with the cooking mode.

Do the light turn off eventually or not at all when you depart? Motion is not detected? If you have a lot of lights there could be performance issues when you turn all on/off at the same time.

**Comment by pointlevel** [comment]
> I have (and you have copied) a "state: turn_off" between sunrise +01:30 and sunset -01:30.
Yes, but shouldn´t the light turn back on 01:30 before sunset anyway?

> Do the light turn off eventually or not at all when you depart? Motion is not detected? If you have a lot of lights there could be performance issues when you turn all on/off at the same time.
I dont have so many lights included...yet. Would it be possible for permormance reasons to include some setting like "presence_on_off_delay" in seconds so its possible to choose when the lights should act. Hallway: 0, Kitchen: 2, Livingroom: 3. etc? 
Should be a little more natural turn on /off of the house also, instead of getting completely dark/light at the same time.

**Comment by pointlevel** [comment]
Look at this history, the "normal"-lights are not turning off when away. The motions registered is the vacuum-cleaner doing its job. 

![Skärmbild 2024-11-19 102631](https://github.com/user-attachments/assets/2699218a-e79f-475f-b506-5377f8f959c6)

**Comment by Pythm** [comment]
I am not able to trigger this on any of my lights. Can you check lux value (below 3000) when you expect light to turn on.

The delay to turn off lights is not priority for now...

Can I ask what system you are running Home Assistant on? Is the Appdaemon an addon or your own docker or similar? The lights are Philips Hue connected to zigbee?

With all the features I have added I fear that it is growing to heavy, especially for Raspberry Pi running with everything as addons...

**Comment by pointlevel** [comment]
Im running HomeAssistant OS on a Lenovo Thinkcentre pc. Both Appdaemon and MQTT is addons to ha, but i hardly think that it should be any problem as it is now with performance. Quite slimmed HA with not much functionality. I have been struggling to get the perfect lightsystem for a long time so that have been in focus.
I have both Philips Hue and Ikea lightbulbs.

**Comment by Pythm** [comment]
Thanks for info! It would be strange if that set-up is not up to the task. I'll need to dig deeper.

My worries are more towards sd cards in combination with "json_path" to save persistent storage. That part is not good coding, so you could try to comment out that line in every room and see if that helps. That would give me an great indication that I need to change it. I am running everything in LXC's in Proxmox and most calls are outside HA directly to zigbee2MQTT.

Persistent is only used to store data from MQTT / Lux and what lightmode is active, for reboots. It reads/writes to disk for every light when turned on or off to store. The lightmode will then be set to normal/away/media depending on presence and if media player is on. I can implement a get_state from HA lux sensors during initialization so not every light gets turned on during day reboot also.

If you have kids, and tend to do updates/reboots when they are asleep, leave the persistent in those rooms to keep nightmode after reboot..

I have started working on the "reset" mode, that brings in more writing to storage so I am rewriting to remove read/write to disk where possible to find some improvements before the next release.

My second thought was flooding the zigbee network, but if you do not have that much, it would be strange if the bulbs have decent connection.

For the delay idea to have rooms turn off in sequence, it will be implemented as an option for the room with seconds to delay setting away mode.

**Comment by Pythm** [comment]
Getting that configuration correct is the biggest problem with this app. There might be implemented a response from HA in a future Appdaemon release on service calls and if so, I might be able to log an error or similar. For now I do not think I will be able to fix it.

The best way I have found in HA to see what light_data you can send is in Developer Tools -> State. 
![image](https://github.com/user-attachments/assets/c5a97745-6169-40de-989d-06f89ab22eb7)

I will update the title and keep this issue open for now.

**Comment by Pythm** [comment]
Is that for the light that did not work? I tried to set 'color_temp_kelvin' to my lightstrip when I was trying to figure a previous issue you had, and it worked then. And to be sure I was setting thru HA lights I tried again now, and it still works. The kelvin temp is not in my supported color modes.

**Comment by Pythm** [comment]
All attributes are sent in a dictionary. It might be possible to create a "IkeaLights" in addition to Lights, MQTTlights and ToggleLights, that sends multiple commands with delay between if more than one, but you could try to get around it as the app is now.

First check if it only applies when you use transition with light data containing both brightness and color_temp_kelvin but no transition. It that works you can have a smoother transitions with two separate times in the seconds before, one with brightness and transition, and the other with color_temp_kelvin and transition. Just add some extra seconds between the two transitions to be sure the transition for the previous is finished before calling next. The one remaining problem will then be that the turn on will be without transition.

```yaml
      - time: 'sunset - 01:30:00'
        light_data:
          brightness: 40
          transition: 3
      - time: 'sunset - 01:30:05'
        light_data:
          color_temp_kelvin: 2700
          transition: 3
      - time: 'sunset - 01:30:10'
        light_data:
          brightness: 40
          color_temp_kelvin: 2700
```

It it only supports color_temp you have some conversion to do...
