### ISSUE TITLE
When using Adaptive Lighting on both mode and motion, motion will turn down brightness if motion settings results in lower brightness than mode brightness does.

### ISSUE THREAD

**Issue by Pythm** [Pythm/ad-Lightwand#16]
Many thanks for the update. 

Tested it now and i think i can see a little problem (or misconfig maybe?)
When im activating my cooking mode in the kitchen it only works when there is no motion, wich seems like unuseful because im always cooking when im in the kitchen :) The motion mode seems to take over.
It works when there is no motion.

Something that i can config to change?

_Originally posted by @pointlevel in https://github.com/Pythm/ad-Lightwand/discussions/15#discussioncomment-11768830_

**Comment by Pythm** [comment]
**Brightness Configuration Considerations for Adaptive Lighting**

When using Adaptive Lighting in automations, modes or motion lights, Lightwand does not know what brightness values Adaptive Lighting will set. This can lead to unexpected behavior, such as the brightness turning down during motion.

To mitigate this issue, I have introduced a workaround in version 1.3.6. However, there are some limitations and considerations to be aware of:

* When using motion lights with Adaptive Lighting, Lightwand does not check if the brightness set by motion light is higher than normal automations.
* If no `max` value is configured for motion, the light will be set to the brightness specified in Adaptive Lighting.

**Combining Modes and Motion Lights**

When switching between modes or using motion lights, the following logic applies:

* **Mode:** If not using Adaptive Lighting, Lightwand considers the maximum brightness (`mode max`) when evaluating conditions.
* **Motion:** If no minimum value is configured for motion, the "mode min" value is treated as -1 during evaluation.

The conditions for setting mode or motion are as follows:

| Condition | Result |
| --- | --- |
| Motion `max` > Mode `max` & Motion `min` ≥ Mode `min` | Set motion |
| Motion `max` > Mode `max` (no min configured for motion) | Set motion |
| Mode `max` > Motion `max` & Mode `min` ≥ Motion `min` | Set mode |
| Mode `max` > Motion `max` (no min configured for motion) | Set mode |

**Reporting Issues**

If you experience any unwanted behavior when using configurations that should work, please comment the issue and your config.

**Comment by pointlevel** [comment]
So if i understand this correct, if i have a mode to set the lights lower than motion, its not possible when using adaptive? Lets say i want some cozy-mode in the livingroom with dimmed down lights for example.

**Comment by pointlevel** [comment]
With this config it almost works. One problem is that the "Kitchen Bench Lamp" doesnt crank it up to 255 when activating cooking mode while there is motion in the kitchen. When there is no motion it works as expected. This light doesnt have any adaptive included as you can see in my config below.
When i activating motion during cooking-mode (Which never would happen normally in my scenario) it at least stays at cooking-level. 

```yaml
MQTTLights:
    - lights:
        - zigbee2mqtt/Kitchen Motion Lamps

      automations:
        - state: adaptive
          max_brightness: 20
          min_brightness: 5

      motionlights:
        state: adaptive
        max_brightness: 80
        min_brightness: 40

      light_modes:
        - mode: cooking
          state: adaptive
          max_brightness: 100
          min_brightness: 95

      lux_constraint: 1000

    - lights:
        - zigbee2mqtt/Kitchen Bench Lamp

      motionlights:
        - time: "00:00:00"
          light_data:
            brightness: 50
            transition: 1

      light_modes:
        - mode: cooking
          light_data:
            brightness: 255
            transition: 1
```

Suggestion: Change the variable "max_brightness" and "min_brightness" to "max_brightness_pct" and "min_brightness_pct" for the adaptive settings because they are percentages.

**Comment by Pythm** [comment]
> So if i understand this correct, if i have a mode to set the lights lower than motion, its not possible when using adaptive? Lets say i want some cozy-mode in the livingroom with dimmed down lights for example.

It will set mode when there is no motion, and if you set mode max > motion min, the motion will not fire.
I can implement motion to set mode if both max/min checks fails. It might break other lights, if so please report and I can remove it again.

**Comment by Pythm** [comment]
> With this config it almost works. One problem is that the "Kitchen Bench Lamp" doesnt crank it up to 255 when activating cooking mode while there is motion in the kitchen. When there is no motion it works as expected. This light doesnt have any adaptive included as you can see in my config below. When i activating motion during cooking-mode (Which never would happen normally in my scenario) it at least stays at cooking-level.
> 
> Suggestion: Change the variable "max_brightness" and "min_brightness" to "max_brightness_pct" and "min_brightness_pct" for the adaptive settings because they are percentages.

Setting higher brightness with mode when motion I also spottet during Christmas so I fixed it, but It might have been broken with the adaptive update...

I will make a "breaking change" to implement "_pct" for adaptive max and min.

**Comment by Pythm** [comment]
> ```yaml
> MQTTLights:
>     - lights:
>         - zigbee2mqtt/Kitchen Bench Lamp
> 
>       motionlights:
>         - time: "00:00:00"
>           light_data:
>             brightness: 50
>             transition: 1
> 
>       light_modes:
>         - mode: cooking
>           light_data:
>             brightness: 255
>             transition: 1
> ```
> 

I just spottet that you have set up motionlight with automations. If you only have one brightness for the motion you can skip time like this:

```yaml
       motionlights:
         light_data:
           brightness: 50
           transition: 1
 ```

Then setting brightness to mode when motion should work.. I will also try to fix the one with time automation

**Comment by pointlevel** [comment]
> I just spottet that you have set up motionlight with automations. If you only have one brightness for the motion you can skip time like this:
> 
> ```yaml
>        motionlights:
>          light_data:
>            brightness: 50
>            transition: 1
> ```
> 
> Then setting brightness to mode when motion should work.. I will also try to fix the one with time automation

There is no difference, cooking mode is not fired on the bench lamp with above config if motion is on.

**Comment by pointlevel** [comment]
Sorry, but with 1.3.7 it got even worse. Including pictures here so you can see for yourself.

In this screenshot, the motionlights (Köksön och Fläktbelysning) is to high, 47% when it should be a maximum of 10% when no motion.
![image](https://github.com/user-attachments/assets/0b479c33-9b0a-4c17-8dd4-e7382cae09e8)

And here the fake motion is activated, and it cranks up by 5% to 52%. This could be right though because the config is between 50-80%.
![image](https://github.com/user-attachments/assets/17bfaf52-0d24-4137-8422-8bd0b41aa3ce)

And finally when im activating "cooking"-mode when motion, nothing happens at all. It works when its no motion.
And when im activating normal mode again, the motionlights is decreased to 89% from i dont know. And the bench light goes back to 0, as it should.

**Comment by Pythm** [comment]
I found one place I forgot to change the min_brightness to min_brightness_pct.. I will revert the change if both max checks fails. But I can include a 'noMotion' option to configure in mode when you use adaptive.

I have started to create a wiki page where I try to gather all info around configuring with Adaptive Lighting to make it a little bit easier to find the information...

I will need to revisit the mode when motion later when I can use one of the lights to test with...

**Comment by pointlevel** [comment]
I updated the missing min_brightness and now that seems to work. 

But i found that when activating cooking mode during motion, i get: 

```
2025-01-13 06:39:55.014817 WARNING HASS: Error calling Home Assistant service default/adaptive_lighting/change_switch_settings
2025-01-13 06:39:55.014988 WARNING HASS: Code: 400, error: 400: Bad Request
```
But only during motion. If i activate the mode during no_motion, it doesnt throw that error. Is it possible that LW thinks that the Kitchen Bench Lamp is included in the adaptive for some reason? That light is off during no_motion and on during motion.

**Comment by Pythm** [comment]
Great. I will start on the noMotion option. I belive it will make more sense in configuration, and keep the max vs max check as it was?

I suspect the error is because Lightwand is sending wrong values and it could be because motion has adaptive and a mode does not? Or only max brightness is configured for mode? I at least found an error there... I did not see it in your code above but if you have other lights configured like that?

I'll need to revisit the adaptive motion/mode code and update the documentation.

**Comment by pointlevel** [comment]
Thanks for the update. It works as expected....almost. When i activate cooking, the lights goes up to the desired level, but when i run "reset_kitchen", the motion lights goes back, but not the bench lamp that doesnt use adaptive. It stays at the same high level.
The above only applies when there is motion in the room. When there is no motion, it works with cooking mode.

```yaml
MQTTLights:
    - lights:
        - zigbee2mqtt/Kitchen Motion Lamps

      adaptive_switch: switch.adaptive_lighting_kitchen_motion

      automations:
        - state: adaptive
          max_brightness_pct: 10
          min_brightness_pct: 5

      motionlights:
        state: adaptive
        max_brightness_pct: 80
        min_brightness_pct: 50

      light_modes:
        - mode: cooking
          state: adaptive
          max_brightness_pct: 100
          min_brightness_pct: 95

      lux_constraint: 1000

    - lights:
        - zigbee2mqtt/Kitchen Bench Lamp

      motionlights:
        light_data:
          brightness: 50
          transition: 1

      light_modes:
        - mode: cooking
          light_data:
            brightness: 250
            transition: 1
```

**Comment by pointlevel** [comment]
Is transition possible to use with adaptive lights?

**Comment by Pythm** [comment]
Yes, that is by design when using Lightwand to set brightness. As long as there is motion Lightwand will not turn down brightness. You requested the option to dim_while_motion for your Livingroom to enable Lightwand to turn brightness down when brightness.

Lightwand only gives Adaptive Lights control so you'll need to check their documentation. This would then apply when you change max and min brightness. Check if changing `initial_transition` in Adaptive Lighting configuration does what you want...

**Comment by Pythm** [comment]
The code for not turning down brightness was initially for when a motion was set up with automation to have different brightness levels during the day. When changing the mode you might want the light to dim, and with control of each room there is less likelihood of turning down the light where the wife is, so I will look into it.

**Comment by pointlevel** [comment]
> Yes, that is by design when using Lightwand to set brightness. As long as there is motion Lightwand will not turn down brightness. You requested the option to dim_while_motion for your Livingroom to enable Lightwand to turn brightness down when brightness.

But turn down brightness if a mode sets it higher temporary and later is deactivated seems like it should. In my opinion it should go back to actual motionlight brightness. I have the dim_while_motion option also.

**Comment by Pythm** [comment]
I need to stop being hasty with replies. Was trying to post before getting the kid to bed. Sorry.

I was looking at the code now and the 'dim_while_motion' only applies if motionlight is configured as a automation (with times). It is also a bigger rewrite to turn back to normal motion from a mode when motion is active if motionlight is configured as automation. I can try to implement that the light goes back to motion setting, when configured as your Bench Lamp, when leaving a mode first and look at when the motion is configured as automation after.

**Comment by pointlevel** [comment]
Hi, updated to latest 1.4.0, but it seems that my motionlights stopped working. Its working for my "Kitchen Bench Lamp" but not "Kitchen Motion Lamps". They just stays at the normal automation. See config below.

```yaml
kitchen:
  module: lightwand
  class: Room
  json_path: /homeassistant/.storage/

  MQTT_namespace: mqtt

  mode_turn_off_delay: 10
  mode_turn_on_delay: 10

  OutLuxMQTT: "zigbee2mqtt/Frontporch Motion Sensor"

  motion_sensors:
    - motion_sensor: binary_sensor.activity_in_kitchen
      delay: 10
    - motion_sensor: input_boolean.fake_activity_in_kitchen
      delay: 1

  options:
    - dim_while_motion

  MQTTLights:
    - lights:
        - zigbee2mqtt/Kitchen Motion Lamps

      adaptive_switch: switch.adaptive_lighting_kitchen_motion

      automations:
        - state: adaptive
          max_brightness_pct: 10
          min_brightness_pct: 5

      motionlights:
        state: adaptive
        max_brightness_pct: 80
        min_brightness_pct: 50

      light_modes:
        - mode: cooking
          state: adaptive
          max_brightness_pct: 100
          min_brightness_pct: 95

      lux_constraint: 1000

    - lights:
        - zigbee2mqtt/Kitchen Bench Lamp

      motionlights:
        light_data:
          brightness: 50
          transition: 1

      light_modes:
        - mode: cooking
          light_data:
            brightness: 250
            transition: 1

    - lights:
        - zigbee2mqtt/Kitchen Window Lamps
      automations:
        - time: "00:00:00"

      light_modes:
        - mode: on_kitchen

      lux_constraint: 800

  Lights:
    - lights:
        - light.kitchen_ceiling_cooking_area

      automations:
        - time: "00:00:00"
          state: turn_off

      light_modes:
        - mode: cooking
```
