### ISSUE TITLE
Setting Mode for only one room

### ISSUE THREAD

**Issue by whirlfire** [Pythm/ad-Lightwand#17]
First of all, thanks for your great work!

I want to set modes per Room. E.g. I have a mode "Bright" in every room, but do not necessarily want to set that at once in the whole house.

Unfortunately, this is only possible with the hardcoded "morning/off/normal/reset".
In fact, its the other way round, there are very few modes I want to set to everything.

Could this be changed, so any mode can be called with <mode>_<roomname>?

Or better: let me define a selector helper in HomeAssistant per Room, which contains the current mode (I have that anyway). That way I could skip creating the automation that triggers events based on that.

**Comment by Pythm** [comment]
I can look into implementing a check for underscore in names, and then only change mode if the room name equals what is behind the underscore. It would break any modes or rooms with underscores in their mode/room names like morning_workday or livingroom_tv.

If you only want to call it pr room then you can name the mode BrightNameMyRoom for each room you want to have the Bright mode, but you will then need to create scripts that call multiple modes in sequence if you want to call Bright mode for more than one room with one action.

This is in Norwegian but you'll get the idea:
```yaml
stue_kjokken_lights_off:
  alias: "Stue og Kjøkken av"
  icon: "mdi:lightbulb-off"
  sequence:
    - event: MODE_CHANGE
      event_data:
        mode: 'off_stuelys'
    - delay:
        seconds: 1
    - event: MODE_CHANGE
      event_data:
        mode: 'off_kjokkenlys'
    - delay:
        seconds: 1
    - event: MODE_CHANGE
      event_data:
        mode: 'off_stuelys_tv'
```


I did find a error in the code when checking for room name that I was planning to release tomorrow. Seems like Python equal checked if mode contained off_ or self.name (roomname) and not combined them to one string so any rooms with 'off_' as mode would then set the new mode.
```python
if self.LIGHT_MODE == 'off_' + str(self.name)
```

The selector helper is a good idea! Should be easy enough to set up a listener based on a configuration input where you'll define the selector.
