### ISSUE TITLE
Allow night motion pr light in room

### ISSUE THREAD

**Issue by Pythm** [Pythm/ad-Lightwand#8]
Add configuration option to allow motion light on selected lights in a room

**Comment by pointlevel** [comment]
Great work with all the updates!
How would i config this light to use the new feature with nigt_motion to turn this on during night.

```yaml
- lights:
        - light.master_bedroom_bed_led # Supports color_temp and xy
      automations:
        - time: "05:30:00"
          light_data:
            brightness: 50
            transition: 3
            color_temp_kelvin: 2200
        - time: "sunrise - 00:40:00"
          dimrate: 1
          light_data:
            brightness: 60
            transition: 3
            color_temp_kelvin: 2200
        - time: "08:30:00"
          orLater: "sunrise + 00:15:00" 
          light_data:
            brightness: 50
            transition: 3
            color_temp_kelvin: 2700
        - time: "sunset - 01:30:00"
          light_data:
            brightness: 100
            transition: 3
            color_temp_kelvin: 2700
        - time: "sunset + 00:30:00"
          orLater: "21:00:00"
          dimrate: 2 
          light_data:
            brightness: 5
            transition: 3

      light_modes:
        - mode: night_master_bedroom
          state: turn_off

      lux_constraint: 2000
```

**Comment by Pythm** [comment]
Same indent as other configurations for the light. And remember to configure motionlights. Maybe best to set light_data?

It should not dim down lights during normal day automation, but if the brightness is the same or higher than normal, it probably will change color / color-temp if you configure that.

```yaml
    - lights:
        - light.master_bedroom_bed_led # Supports color_temp and xy
      automations:
        - time: "05:30:00"
          light_data:
            brightness: 50
            transition: 3
            color_temp_kelvin: 2200
        - time: "sunrise - 00:40:00"
          dimrate: 1
          light_data:
            brightness: 60
            transition: 3
            color_temp_kelvin: 2200
        - time: "08:30:00"
          orLater: "sunrise + 00:15:00" 
          light_data:
            brightness: 50
            transition: 3
            color_temp_kelvin: 2700
        - time: "sunset - 01:30:00"
          light_data:
            brightness: 100
            transition: 3
            color_temp_kelvin: 2700
        - time: "sunset + 00:30:00"
          orLater: "21:00:00"
          dimrate: 2 
          light_data:
            brightness: 5
            transition: 3

      motionlights:
          light_data:
            brightness: 5
            transition: 3
            color_temp_kelvin: 2200

      light_modes:
        - mode: night_master_bedroom
          state: turn_off

      lux_constraint: 2000

      options:
        - night_motion
```
